<!-- список партнеров -->
<a class="partners-item smi2" title="smi2.ru" href="http://smi2.ru?utm_source=forbes_ru&utm_medium=referral&utm_campaign=blockchain" target="_blank"></a>
<a class="partners-item lefotu" title="lefotu.com" href="http://lefotu.com/?utm_source=forbes&utm_medium=referral&utm_campaign=blockchain" target="_blank"></a>
<a class="partners-item interfax" title="interfax.ru" href="http://www.interfax.ru/?utm_source=forbes&utm_medium=referral&utm_campaign=blockchain" target="_blank"></a>
<a class="partners-item tass" title="tass.ru" href="http://tass.ru?utm_source=forbes&utm_medium=referral&utm_content=1&utm_campaign=blockchain" target="_blank"></a>
<a class="partners-item gva" title="gva.vc" href="http://www.gva.vc/ru/?utm_source=forbes&utm_medium=referral&utm_campaign=blockchain" target="_blank"></a>
<a class="partners-item forklog" title="forklog.com" href="http://forklog.com/?utm_source=forbes&utm_medium=referral&utm_campaign=blockchain" target="_blank"></a>
<a class="partners-item anycoin" title="anycoin.news" href="http://anycoin.news?utm_source=forbes_ru&utm_medium=referral&utm_campaign=blockchain" target="_blank"></a>
<a class="partners-item if24" title="if24.ru" href="http://www.if24.ru/?utm_source=forbes_ru&utm_medium=referral&utm_campaign=blockchain" target="_blank"></a>
<a class="partners-item coinspot" title="coinspot.io" href="http://coinspot.io/?utm_source=forbes&utm_medium=referral&utm_campaign=blockchain" target="_blank"></a>
<a class="partners-item bitjournal" title="bitjournal.media" href="http://bitjournal.media/?utm_source=forbes&utm_medium=referral&utm_campaign=blockchain" target="_blank"></a>
<a class="partners-item bitnewstoday" title="bitnewstoday.ru" href="http://bitnewstoday.ru/?utm_source=forbes&utm_medium=referral&utm_campaign=blockchain" target="_blank"></a>
<a class="partners-item cryptorussia" title="cryptorussia.ru" href="http://cryptorussia.ru/?utm_source=forbes&utm_medium=referral&utm_campaign=blockchain" target="_blank"></a>
<a class="partners-item bitcryptonews" title="bitcryptonews.ru" href="http://bitcryptonews.ru?utm_source=forbes&utm_medium=referral&utm_campaign=blockchain" target="_blank"></a>
<a class="partners-item techfusion" title="techfusion.ru" href="http://techfusion.ru/?utm_source=forbes&utm_medium=referral&utm_campaign=blockchain" target="_blank"></a>
<a class="partners-item procrypto" title="Pro_Crypto" href="https://t.me/Pro_Crypto" target="_blank"></a>
<a class="partners-item iksmedia" title="iksmedia.ru" href="http://iksmedia.ru?utm_source=forbes&utm_medium=referral&utm_campaign=blockchain" target="_blank"></a>
<a class="partners-item bitnovosti" title="bitnovosti.com" href="http://bitnovosti.com/?utm_source=forbes&utm_medium=referral&utm_campaign=blockchain" target="_blank"></a>
<a class="partners-item finmarket" title="finmarket.ru" href="http://www.finmarket.ru/?utm_source=forbes&utm_medium=referral&utm_campaign=blockchain" target="_blank"></a>
<a class="partners-item coinews" title="finmarket.ru" href="http://www.finmarket.ru/?utm_source=forbes&utm_medium=referral&utm_campaign=blockchain" target="_blank"></a>
<a class="partners-item bloomchain" title="bloomchain.ru" href="https://bloomchain.ru?utm_source=forbes&utm_medium=cpc&utm_campaign=blockchain" target="_blank"></a>
<a class="partners-item fomag" title="fomag.ru" href="http://fomag.ru/?utm_source=forbes&utm_medium=cpc&utm_campaign=blockchain" target="_blank"></a>
<a class="partners-item bankstoday" title="bankstoday.net" href="https://bankstoday.net?utm_source=forbes&utm_medium=cpc&utm_campaign=blockchain" target="_blank"></a>
<a class="partners-item bitsmedia" title="bits.media" href="https://bits.media/?utm_source=forbes&utm_medium=cpc&utm_campaign=blockchain" target="_blank"></a>
<a class="partners-item nsd" title="nsd.ru" href="https://www.nsd.ru?utm_source=forbes&utm_medium=cpc&utm_campaign=blockchain" target="_blank"></a>
<a class="partners-item retailru" title="retailru" href="https://www.retail.ru/?utm_source=forbes&utm_medium=referral&utm_campaign=bigdata" target="_blank"></a>
<a class="info-partners kv" title="kv.by" href="https://www.kv.by/?utm_source=forbes&utm_medium=partner&utm_campaign=bigdata" target="_blank"></a>
<a class="info-partners ibs" title="ibs.ru" href="https://www.ibs.ru/?utm_source=forbes&utm_medium=referral&utm_campaign=bigdata" target="_blank"></a>
<a class="info-partners mylab" title="mylab.club" href="http://www.mylab.club/?utm_source=forbes&utm_medium=referral&utm_campaign=bigdata" target="_blank"></a>
<a class="info-partners amr" title="amr.ru" href="http://amr.ru" target="_blank"></a>
<a class="info-partners cfo" title="cfo-russia.ru" href="http://www.cfo-russia.ru?utm_source=forbes&utm_medium=referral&utm_campaign=bigdata" target="_blank"></a>
<a class="info-partners itpark" title="www.itpark-kazan.ru/ru" href="https://www.itpark-kazan.ru/ru?utm_source=forbes&utm_medium=referral&utm_campaign=bigdata" target="_blank"></a>
<a class="info-partners finoman" title="telegram.me/finoman" href="https://telegram.me/finoman?utm_source=forbes&utm_medium=referral&utm_campaign=bigdata" target="_blank"></a>
<a class="info-partners franchai" title="franchay.ru" href="http://franchay.ru/?utm_source=forbes&utm_medium=referral&utm_campaign=bigdata" target="_blank"></a>
<a class="info-partners infostart" title="cfo-russia.ru" href="https://infostart.ru/?utm_source=forbes&utm_medium=referral&utm_campaign=bigdata" target="_blank"></a>
<a class="info-partners metropol" title="metropol-moscow.ru" href="http://metropol-moscow.ru/?utm_source=forbes&utm_medium=referral&utm_campaign=bigdata" target="_blank"></a>
